language: csharp
mono:
  - latest
  - 3.12.0
  - 3.10.0
script:
  - xbuild /p:TargetFrameworkVersion="v4.0" ./XVM_EnableGoldFreeXPLocker/XVM_EnableGoldFreeXPLocker.sln
  - msbuild /p:Configuration=Release ./XVM_EnableGoldFreeXPLocker/XVM_EnableGoldFreeXPLocker.sln
  - mono ./XVM_EnableGoldFreeXPLocker/XVM_EnableGoldFreeXPLocker/bin/Release/XVM_EnableGoldFreeXPLocker.exe